### ISSUE TITLE
Problem deploying project searchlight

### ISSUE THREAD

**Issue by jfmonteil** [Pentaho-SE-EMEA-APAC/part#216]
Hello I have this error while deploying searchlight, my connection points to a JDBC towards postgres...

C:\Program Files\part\demo-project-searchlight>part deploy -env local
C:\Users\jmonteil\.part\part.log
INFO : PART command: deploy
INFO : The following schema will be created. This WILL destroy all existing schema structure and data:-
INFO :  - SEARCHLIGHTDB._noschemaname
INFO :  - SEARCHLIGHTDB.public
INFO : Do you wish to proceed with this destructive operation? Answer 'Y' or 'N'. (Default N)
Y
FATAL: Unsupported JDBC data type '1' for column 'isboolean'. Stopping.
FATAL: Failed to deploy schema 'SEARCHLIGHTDB._noschemaname'. Abandoning.
INFO : deploy failed to completed successfully
INFO : deploy completed in 2,492 seconds

**Comment by jfmonteil** [comment]
Note I have the same error if I create the searclightdb connection in MySQL

**Comment by adamfowleruk** [comment]
This is an issue with the project, not part. please report there.

As a workaround, delete the datasources/*/_noschemaname files and directories, and try again.
